//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCISA_Test.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCISADBEntities : DbContext
    {
        public SCISADBEntities()
            : base("name=SCISADBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Test_Access> Tbl_Test_Access { get; set; }
        public virtual DbSet<Tbl_Test_Dates> Tbl_Test_Dates { get; set; }
        public virtual DbSet<Tbl_Test_Doctors> Tbl_Test_Doctors { get; set; }
        public virtual DbSet<Tbl_Test_Patients> Tbl_Test_Patients { get; set; }
        public virtual DbSet<Tbl_Test_Roles> Tbl_Test_Roles { get; set; }
        public virtual DbSet<Tbl_Test_Users> Tbl_Test_Users { get; set; }
    }
}
