//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCISA_Test.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Test_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Test_Roles()
        {
            this.Tbl_Test_Access = new HashSet<Tbl_Test_Access>();
            this.Tbl_Test_Users = new HashSet<Tbl_Test_Users>();
        }
    
        public int Int_Id { get; set; }
        public string Chr_Name { get; set; }
        public bool Bit_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Test_Access> Tbl_Test_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Test_Users> Tbl_Test_Users { get; set; }
    }
}
